### ISSUE TITLE
Missing "nuget_icon2.png" & Bug with any .png file if pointed correctly!

### ISSUE THREAD

**Issue by Special-Niewbie** [DigitalAdeel/MaterialSkin2DotNet#10]
Hi, I was looking for a package for Visual Studio and Winform, which gives me more customization with MaterialSkin colors, and I think I found your project. I wanted to try it, but if I try to compile it, I get an error that the icon nuget_icon2 is missing, as below:

`Error NU5046 The icon file 'nuget_icon2.png' does not exist in the package. MaterialSkin2DotNet C:\Program Files\dotnet\sdk\7.0.103\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets 221`.

Inside the project doesnt'exist the "nuget_icon2.png", so I have tried anything, even to modify the ".png" resolution and re-name it, I have add in different way to point the file.png  correctly for the "PATH" from the ".csproj" and even from "C:\MaterialSkin2DotNet-1.0.3\MaterialSkin2DotNet\obj\Debug\MaterialSkin2DotNet.1.0.3.nuspec"; but nothing, it gives me the same error that cannot find the file but the file it's THERE.

Have you any idea, if it's a problem of some kind of bug or what so ever?

Have nice day.

**Comment by DigitalAdeel** [comment]
Hi and just uncheck 
"Produce a package file during build operations." in it's Property's Package Tab  and then rebuild :)

![image](https://user-images.githubusercontent.com/74082224/221116791-585ab9f1-22ad-4685-af5f-bd9db31cdd71.png)

**Comment by DigitalAdeel** [comment]
@Special-Niewbie Lemme know if that fixes the issue :)

**Comment by Special-Niewbie** [comment]
> @Special-Niewbie Lemme know if that fixes the issue :)

Hi @DigitalAdeel , thank you very much to repled me :) . I have tried to do as per you suggestion and come out this error now: 

![lK1gN](https://user-images.githubusercontent.com/64843123/221121744-e00ad2ce-10ba-4540-b717-fb0a4a7c6a5a.png)

The picture Error, it's just reference error that I found in internet because my Visual Studio it's not in English, but anyway it shows the same error. I'm tryng your version 1.0.3, because on your main GitHub page project you have the old 1.0.2. 

Thank you very much for support me👍

**Comment by DigitalAdeel** [comment]
No Problem, I'm glad that you liked it :)
It's giving you that error because it's a Class Library not an Executable Program, so all you can do with class library is build it and then reference it's dll in the project where you wanna use it :)

**Comment by DigitalAdeel** [comment]
@Special-Niewbie  You'll find Dll in Debug/Release folder once you build/rebuild it.

![image](https://user-images.githubusercontent.com/74082224/221126641-42b2e900-e140-4876-8e7c-05cfc9ae41b4.png)

**Comment by DigitalAdeel** [comment]
Lemme know if you wanna ask something :)

**Comment by DigitalAdeel** [comment]
Master Branch got the source code of the 1.1.2 nuget version

![image](https://user-images.githubusercontent.com/74082224/221166017-9cf406a0-0c24-4a5f-96c6-a569eae8f6df.png)

**Comment by Special-Niewbie** [comment]
> @Special-Niewbie  Lemme know if you wanna ask something :)

Yes, forgive me but I'm away from home and then I'll come back and try.  In the meantime, I try to answer you here with my phone.  Since I'm new to these packages for Visual Studio;  I don't understand one thing this project that extends the MaterialSkin functionality .... do I have to install the MaterialSkin project in combination with yours, or does your project give the functions (as you mentioned) in .dll including the MaterialSkin objects?  And then I saw that from Visual Studio your latest version doesn't install from the packages and it comes with errors, for this reason I'm trying to do something with your source code.  Forgive me for the questions, but try to understand me that for me it's a new world Visual Studio... Cheers

**Comment by DigitalAdeel** [comment]
No. I developed this completely from scratch by copy pasting the code from MaterialSkin.2's repo in to new .NET Core Project, so you don't need to install MaterialSkin.2 Nuget for it.

Only my MaterialSkinDataTable
 needs MaterialSkin.2 nuget because that I developed separately with .NET Framework which MaterialSkin.2 uses.

MaterialSkin2DotNet got it's own MaterialSkinDataTable control, so no need to install anything else.

**Comment by Special-Niewbie** [comment]
> No. I developed this completely from scratch by copy pasting the code from MaterialSkin.2's repo in to new .NET Core Project, so you don't need to install MaterialSkin.2 Nuget for it.
> 
> Only my MaterialSkinDataTable
>  needs MaterialSkin.2 nuget because that I developed separately with .NET Framework which MaterialSkin.2 uses.
> 
> MaterialSkin2DotNet got it's own MaterialSkinDataTable control, so no need to install anything else.

Ok, thank you so much to clear my mind about it, later I will try again to install it without any other MaterialSkin, and let you know. If nothing happens, I will use the .dll file and anyway report to you if any issues. Inthis case good job you did if it's this the case 🙏

**Comment by DigitalAdeel** [comment]
Gracias Hermano :)

**Comment by Special-Niewbie** [comment]
Ok @DigitalAdeel , I just comeback and seatdown in front of the PC; maybe I understand my problem, if I try to install your package 1.1.2 from the package NeGet manager it comes out this error `Error The package 'MaterialSkin2DotNet 1.1.2' could not be installed. You are trying to install into a project targeting '.NETFramework,Version=v4.7.1', but the package does not contain references to framework compatible assemblies or data files. For more information, contact the author of the package.` Have means that your package it's not compatible with .NETFramework 4.7.1?

**Comment by DigitalAdeel** [comment]
Because you create project with .NETFramework but my nuget uses .NETCore3.1

**Comment by DigitalAdeel** [comment]
Latest .NETCore versions supported my nugets are:
.NETCORE 3.1
.NET 5,6,7

**Comment by DigitalAdeel** [comment]
As you can see, Two WinForms Templates, First one uses new .NET(core) where .NET Framework uses old versions.
![image](https://user-images.githubusercontent.com/74082224/221179572-77954f55-f148-4ef7-a22a-10509246ab69.png)

**Comment by Special-Niewbie** [comment]
> As you can see, Two WinForms Templates, First one uses new .NET(core) where .NET Framework uses old versions.
> ![image](https://user-images.githubusercontent.com/74082224/221179572-77954f55-f148-4ef7-a22a-10509246ab69.png)
> 

Yeap, I can see now thank you very much, this from one side it's nice because will use the latest Frameworks but from another side will take out a lot of project compatibilities. I believe if your project can be compatible with latest versions of 4.7/4.8 as well for sure will get bigger score . There is anyway to port your project to the Framework 4.7/4.8?

**Comment by DigitalAdeel** [comment]
@Special-Niewbie I'll think about it when I'm free :)

**Comment by Special-Niewbie** [comment]
> @Special-Niewbie I'll think about it when I'm free :)

Love you man, thank you very much, if you will do it, I believe you will destroy other NuGet projects, because if in your package there is such personalization, no others projects can be in your level. Have nice day, and thanks a lot to support me 🙏

**Comment by DigitalAdeel** [comment]
De Nada Hermano 💙
All my code with written in .NET Core 3.1, so migrating back up .NET Framework not gonna need that much changes to make :)

**Comment by DigitalAdeel** [comment]
@Special-Niewbie I'll let you know once it's done :)

**Comment by DigitalAdeel** [comment]
And Voila!

![image](https://user-images.githubusercontent.com/74082224/221204733-7802883b-3696-482b-b2b5-ca31cd47c030.png)

**Comment by DigitalAdeel** [comment]
@Special-Niewbie Migrated :)

**Comment by DigitalAdeel** [comment]
Will publish nuget for it soon :)

**Comment by DigitalAdeel** [comment]
@Special-Niewbie  Done :)
https://www.nuget.org/packages/MaterialSkin2Framework

Will be public in few minutes :)
![image](https://user-images.githubusercontent.com/74082224/221212632-cd2bfb19-52c2-4d9d-a7b8-b71edaa43c6c.png)

**Comment by DigitalAdeel** [comment]
![image](https://user-images.githubusercontent.com/74082224/221213237-00c62c51-19e9-4068-9c80-0782273992cc.png)

**Comment by DigitalAdeel** [comment]
De Nada Amigo 😉
If you got any feature request, then I'll be happy to develop it :)
and If you issue is resolved, then close it :)

**Comment by DigitalAdeel** [comment]
@Special-Niewbie https://github.com/DigitalAdeel/MaterialSkin2Framework

**Comment by Special-Niewbie** [comment]
> 

Yes, yes , yes , please........ What can I see that other projects cannot do (including your for now), it's on the Propriety of the object, example the Button it's miss:

1)  Cannot personalize the FillColor of the Actual Base Button Color, what can I see now, I can change just in two colors base Purple and Fuxia but I cannot change to any color.
2) ImageOffest X-Y of the Icon / Image size.
3) The BorderColor and Thikness of the Border Button to manage it.
4) The Ability to change the 4 angles radius of the Button.
5) The HoverState --> FontColor, Image, BorderColor,FillColor.
6) The PressedState --> FontColor, Image, BorderColor,FillColor.
7) And the Animation Circle Color, when you press the actual Button.

These are the ideas that come out in my mind that no one project add and for the Final user prospective it's limitation to don't have such implementation. If you need more Ideas I have others for the Futures. This will make the project really forward in front of others..

**Comment by DigitalAdeel** [comment]
Thanks for the suggestions.
1. Cannot personalize the FillColor of the Actual Base Button Color, what can I see now, I can change just in two colors base Purple and Fuxia but I cannot change to any color.
Because it's color based on Google's Material Design, that's why only color that are added in can be used.
https://m2.material.io/design/color/the-color-system.html

**Comment by DigitalAdeel** [comment]
Open a new issue for the features that you just mentioned :)
I'm closing this issue cuz issue is resolved

**Comment by DigitalAdeel** [comment]
@Special-Niewbie First of all, you need to change the type of From to MaterialForm
![image](https://user-images.githubusercontent.com/74082224/221251153-2a532564-41c3-46a1-a5d9-de3ac9dbd20f.png)

Then you'll have properties for the form in properties grid, where you can change colors including color for buttons and other controls. :)
![image](https://user-images.githubusercontent.com/74082224/221251333-0c31834f-2a1b-48d9-a6b7-46d3c1ac2dea.png)

**Comment by DigitalAdeel** [comment]
@Special-Niewbie  See button color is same as Primary Color of the Form
![image](https://user-images.githubusercontent.com/74082224/221251523-17271b36-867d-4e04-a47b-2ec8608876e2.png)
Now it's Brown500
![image](https://user-images.githubusercontent.com/74082224/221251593-7986c2b7-4dfa-497b-8d41-bb8a083a6bcf.png)

**Comment by DigitalAdeel** [comment]
@Special-Niewbie Button can have either primary or accent color.
To use Access color instead of primary, set it's UseAccentColor property to true :)
![image](https://user-images.githubusercontent.com/74082224/221251777-e8914395-369c-405d-a8c5-2e5fad798923.png)
