### ISSUE TITLE
Scrolling within an empty datatable leads to System.ArgumentOutOfRangeException 

### ISSUE THREAD

**Issue by Dr33v3s** [DigitalAdeel/MaterialSkin2DotNet#11]
Hey man, great work. I've only been using it for a short time but everything looks great and works as expected.

But when i scroll the mouse wheel in a datatable with no values, I get a System.ArgumentOutOfRangeException.

**Comment by DigitalAdeel** [comment]
@Dr33v3s Hi and thanks for reporting :)
I'll add a null checker for it.

**Comment by DigitalAdeel** [comment]
@Dr33v3s Glad that you liked something that I developed cuz the original author didn't 😅
Nowadays, I'm busy doin freelancing projects, that's why I didn't do any bug fixing or added new feature.

**Comment by DigitalAdeel** [comment]
@Dr33v3s Lemme know if you got any feature request or something cuz I might do it in my free time ;)

**Comment by DigitalAdeel** [comment]
@Dr33v3s De Nada Hermano :)

**Comment by DigitalAdeel** [comment]
@Dr33v3s Fixed 😉
![image](https://user-images.githubusercontent.com/74082224/225685639-30afa0dc-4a7c-4652-b8ce-d295c8d7a153.png)

**Comment by DigitalAdeel** [comment]
@Dr33v3s 
The issue has been fixed in commit #a6ad72a . The changes were made to the file MaterialDataTable.cs

**Comment by DigitalAdeel** [comment]
> Thank you for fixing the problem so quickly. And of course thank you very much for the credit.
> 
> You‘re a great guy.

De Nada Amigo :)

FYI: Working on Pagination for MaterialDataTable😉

![image](https://user-images.githubusercontent.com/74082224/225723805-0ab1b9e8-fb6b-497c-b89d-6c6c4d8512c9.png)
