### ISSUE TITLE
 Support for Net Framework 4.7.2 ?

### ISSUE THREAD

**Issue by naakmsc** [DigitalAdeel/MaterialSkin2DotNet#13]
I'm trying to implement it but I have problems installing the package, could you tell me which framework versions are supported?
![image](https://github.com/DigitalAdeel/MaterialSkin2DotNet/assets/71958603/2d29034c-4da9-4165-b1ec-79594f6344c0)

**Comment by DigitalAdeel** [comment]
Hi and you're installing wrong package.
Install MaterialSkin2Framework if you wanna use .NET Framework :)

**Comment by naakmsc** [comment]
I was trying to install this version for the ease of changing the colors since the Ignace Maes version does not allow more than the default list.

**Comment by DigitalAdeel** [comment]
No problem, if your issue is resolved then close it :)
