### ISSUE TITLE
Can you add datagrid and menustrip

### ISSUE THREAD

**Issue by anil-shrestha** [DigitalAdeel/MaterialSkin2DotNet#5]

**Comment by DigitalAdeel** [comment]
Maybe later. I've currently installed macOS on my laptop and WinForms is can be used for Windows only, so when I get time to use Windows again, then I'll focus on updating this repo.

**Comment by DigitalAdeel** [comment]
**WIP: DataTable**
![Screenshot (2)](https://user-images.githubusercontent.com/74082224/125752152-927d5ff1-1ef5-4c8a-8334-a6ab8c5d6559.png)

**Comment by anil-shrestha** [comment]
Good going. Please release soon.

**Comment by DigitalAdeel** [comment]
**I'll, here current status of DataTable.**

![Screenshot (20)](https://user-images.githubusercontent.com/74082224/126434694-70be0717-24e7-4c6c-9254-636d10df7a61.png)

**Comment by DigitalAdeel** [comment]
Busy
