### ISSUE TITLE
Icons doesn't show in drawer menu

### ISSUE THREAD

**Issue by moisesreyes** [DigitalAdeel/MaterialSkin2DotNet#8]
In net6 icons doesn't show in the drawer menu, but in design time the tabs shows the icons.

**Comment by moisesreyes** [comment]
Hi! I solved it, the icon doesn't work if i assign by index, but if i assign it by key it work perfectly.

Thanks for your quick reply.

**Comment by DigitalAdeel** [comment]
@moisesreyes You welcome. I already know about the problem but asked for screenshot just to confirm. Btw Bueno Amigo to solve it yourself 💙.
